
import Head from "next/head";
import CommentModal from "../components/CommentModal";
import Sidebar from "../components/Sidebar";
import Widgets from "../components/Widgets";
import Posts from "../components/Posts";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { collection, query, onSnapshot, orderBy } from "firebase/firestore";
import { db } from "../firebase";
import { useSession } from "next-auth/react";
import ShareModal from "@/components/ShareModal";
import { HiSparkles } from "react-icons/hi";
import { AnimatePresence, motion } from "framer-motion";
import BottomBar from "@/components/BottomBar";

export default function Bookmark({ newsResults }) {
    const router = useRouter();
    const [posts, setPosts] = useState([]);
    const [bookmarks, setBookmarks] = useState([]);
    const { data: session } = useSession();
    var p = [];


    useEffect(() => {
        onSnapshot(
            query(collection(db, "posts"), orderBy("timestamp", "desc")),
            (snapshot) => {
                setPosts(snapshot.docs)
            }
        );
    }, [])

    // get comments of the post



    return (
        <div>
            <Head>
                <title>Post Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="flex min-h-screen mx-auto">
                {/* Sidebar */}
                <Sidebar tab="BookMark" />

                {/* Feed */}
                <div className="xl:ml-[375px] border-l sm:border-r xl:min-w-[576px] sm:ml-[73px] flex-grow max-w-[40rem] border-gray-200">
                    <div className="flex py-2 px-3 sticky top-0 z-50 bg-white border-b border-gray-200">
                        <h2 className="text-lg sm:text-xl font-bold cursor-pointer">BookMarks</h2>
                        <div className="text-green-800 hoverEffect items-center justify-center flex px-0 ml-auto w-9 h-9">
                            <HiSparkles className="h-6" />
                        </div>
                    </div>

                    <AnimatePresence>

                        {posts.map((post) => (<div key={post.id}> {
                            Array.isArray(post.data().bookmarks) && post.data().bookmarks.includes(session?.user?.uid) &&
                            <motion.div
                                key={post.id}
                                initial={{ opacity: 0 }}
                                animate={{ opacity: 1 }}
                                exit={{ opacity: 0 }}
                                transition={{ duration: 1 }}
                            >
                                <Posts id={post.id} post={post} />
                            </motion.div>
                        }

                        </div>

                        ))}

                    </AnimatePresence>
                </div>
                {/* Widgets */}
                <Widgets newsResults={newsResults.articles} />
                {/* Modal */}
                <CommentModal />
                <ShareModal />
                <BottomBar tab="BookMark" />
            </main>
        </div>
    );
}

export async function getServerSideProps() {
    const newsResults = await fetch(
        "https://saurav.tech/NewsAPI/top-headlines/category/general/in.json"
    ).then((res) => res.json());

    return {
        props: {
            newsResults: JSON.parse(JSON.stringify(newsResults)),
        },
    };
}
