import Head from "next/head";
import Sidebar from "@/components/Sidebar";
import Feed from "@/components/Feed";
import Widgets from "@/components/Widgets";
import CommentModal from "@/components/CommentModal";
import BottomBar from "../components/BottomBar";

export default function Home({ newsResults }) {
  return (
    <>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen  mx-auto ">
        {/* sidebar */}
        <Sidebar tab="Home" />
        {/* feed section */}
        <Feed />
        {/* wigets */}
        <Widgets newsResults={newsResults.articles} />
        {/* modal */}
        <CommentModal />
        {/* bottombar  */}
        <BottomBar tab="Home" />
      </main>
    </>
  );
}

// https://saurav.tech/NewsAPI/top-headlines/category/health/in.json

export async function getServerSideProps() {
  const newsResults = await fetch(
    "https://saurav.tech/NewsAPI/top-headlines/category/general/in.json"
  ).then((res) => res.json());

  return {
    props: {
      newsResults: JSON.parse(JSON.stringify(newsResults)),
    },
  };
}
