import Head from "next/head";
import Sidebar from "@/components/Sidebar";
import Feed from "@/components/Feed";
import Widgets from "@/components/Widgets";
import CommentModal from "@/components/CommentModal";
import BottomBar from "../components/BottomBar";
import ShareModal from "@/components/ShareModal";
import {
  collection,
  serverTimestamp,
  setDoc,
  addDoc,
  onSnapshot,
  query,
  orderBy,
  doc,
  where,
} from "firebase/firestore";
import { db } from "../firebase";
import { useState, useEffect } from "react";
import { useSession } from "next-auth/react";

export default function Home({ newsResults }) {
  const [users, setUsers] = useState([]);
  const { data: session } = useSession();

  useEffect(() => {
    if (session && session.user && session.user.uid) {
      onSnapshot(
        query(collection(db, "users"), where("id", "==", session?.user?.uid)),
        async (snapshot) => {
          if (snapshot.empty) {
            await setDoc(doc(db, "users", session?.user?.uid), {
              id: session?.user.uid,
              name: session?.user.name,
              username: session?.user.username,
              userImg: session?.user.image,
              verified: false,
              timestamp: serverTimestamp(),
              bio: "",
              website: "",
              bgImage: "",
              views: 0,
            });
          }
        }
      );
    }
  }, [session]);

  return (
    <>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen  mx-auto ">
        {/* sidebar */}
        <Sidebar tab="Home" />
        {/* feed section */}
        <Feed />
        {/* wigets */}
        <Widgets newsResults={newsResults.articles} />
        {/* modal */}
        <CommentModal />
        <ShareModal />
        {/* bottombar  */}
        <BottomBar tab="Home" />
      </main>
    </>
  );
}

// https://saurav.tech/NewsAPI/top-headlines/category/health/in.json

export async function getServerSideProps() {
  const newsResults = await fetch(
    "https://saurav.tech/NewsAPI/top-headlines/category/general/in.json"
  ).then((res) => res.json());

  return {
    props: {
      newsResults: JSON.parse(JSON.stringify(newsResults)),
    },
  };
}
